config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "posts#index"
  resources :categories
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

	#def after_sign_in_path_for(resource)
	 #   categories_path
	#end

	 before_action :configure_permitted_parameters, if: :devise_controller?

    protected
        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :city, :facebook_url) }
            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :city, :facebook_url) }
        end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  	@categories = Category.all
  end

  def new
  	@category = Category.new
  end

  def create
        @categories = Category.new(categories_params)
        if @categories.save
          flash[:notice] = 'Category created'
            redirect_to categories_path
        else
            render new
        end
  end

  def edit
  	@category = Category.find(params[:id])
  end

  def update
  	@category = Category.find(params[:id])
  	# @category = Category.update_attributes(categories_params)
    if @category.update_attributes(categories_params)
        flash[:notice] = 'Category updated'
        redirect_to category_path
    else
        render new
    end
  end

  def show
  	@category = Category.find(params[:id])
  end

   def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:delete] = 'Category deleted'
    redirect_to categories_path
  end

  private
  		def categories_params
            params.require(:category).permit(:name)
        end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]
  def index
  	@posts = Post.all
  end

  def new
    @categories = Category.all
  	@post = Post.new
  end

  def create
  	 	@posts = Post.new(posts_params)
        if @posts.save
          flash[:notice] = 'Post has been created'
            redirect_to posts_path
        else
            render new
        end
  end

  def edit
  	@post = Post.find(params[:id])
  end

  def update
  	@post = Post.find(params[:id])
  	 if @post.update_attributes(posts_params)
      flash[:notice] = 'Post successfully updated'
        redirect_to post_path
    else
        render new
    end
  end

  def show
  	@post = Post.find(params[:id])
  end

  def destroy
  	@post = Post.find(params[:id])
  	@post.destroy
    flash[:delete] = 'Post deleted'
  	redirect_to posts_path
  end

    private
  		def posts_params
            params.require(:post).permit(:title, :body, :user_id, :category_id)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/edit.html.erb
<div class="container">
	<%= link_to 'All Categories', categories_path, :class=> 'text-primary' %>
	<h1 class="text-center">Edit Category</h1>
	<div class="row">
		<div class="col-sm-7 mx-auto">
		 <%= form_for @category, html: { multipart: true, class: 'form-horizontal' } do |f| %>
		      <div class="field form-group form-row">
		        <%= f.label :name, class: 'col-sm-3' %><br />
		        <%= f.text_field :name, class: 'form-control col-sm-7', placeholder: 'Type Category Name' %>
		      </div>

		    <div class="field form-group form-row">
		        <div class="col-sm-3"></div>
		        <%= f.submit "Update Catgory", class: 'col-sm-7 btn btn-warning' %>
		      </div>
		    <% end %>
		</div>
	</div>
</div>

app/views/categories/index.html.erb
<div class="container">
	<h1>List Of Categories</h1>
	<ul class="list-group list-unstyled w-50">
		<% @categories.each do |c| %>
			<li class="list-group-item bg-dark mb-3"><%= link_to c.name, category_path(c), :class=> 'text-white' %>
				<%= link_to 'Edit', edit_category_path(c), :class=> 'text-warning' %>
			 <%= link_to "Delete", category_path(c), :confirm => "Are you sure you want to delete?", :method => :delete, :class=> 'text-danger' %>
			 	
			 </li>
		<% end %>
	</ul>
	
</div>

app/views/categories/new.html.erb
<div class="container">
	<%= link_to 'All Categories', categories_path, :class=> 'text-primary' %>
	<h1 class="text-center">Make a New Category</h1>
	
	<div class="row">
		<div class="col-sm-7 mx-auto">
		 <%= form_for @category, html: { multipart: true, class: 'form-horizontal' } do |f| %>
		      <div class="field form-group form-row">
		        <%= f.label :name, class: 'col-sm-3' %><br />
		        <%= f.text_field :name, class: 'form-control col-sm-7', placeholder: 'Category Name' %>
		      </div>

		    <div class="field form-group form-row">
		        <div class="col-sm-3"></div>
		        <%= f.submit "Create", class: 'col-sm-7 btn btn-warning' %>
		      </div>
		    <% end %>
		</div>
	</div>
</div>

app/views/categories/show.html.erb
<div class="container">
	<h1 class="text-center"><%= @category.name %></h1>
	<h5>Blog posts in this category</h5>
	<div class="row">
		<% if @category.posts.count > 0 %>
			<% @category.posts.each do |post| %>
				<div class="card mb-3 col-sm-4">
					<div class="card-header">
						<%= link_to post.title, post_path(post) %>
					</div>
					<div class="card-body">
						<%= post.body %>
					</div>
				</div>
			<% end %>
		<% else %>
			<p>No posts in this category yet!</p>
		<% end %>
	
	</div>

	 <p> <%= link_to 'Edit Category', edit_category_path(@category), :class => "text-warning" %> </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mysite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
  
  <%= render "partials/header" %>

  <% if flash[:notice] %>
    <div class="alert-success w-25"><%= flash[:notice] %></div>
  <% end %>
   <% if flash[:delete] %>
    <div class="alert-danger w-25"><%= flash[:delete] %></div>
  <% end %>
   <% if user_signed_in? %>
      <% else %>
    <h5 class="text-danger">Please signin to manage posts and categories</h5>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/partials/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">MySite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
         <%= link_to 'Home', posts_path, :class => "nav-link" %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Categories', categories_path, :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'New Category', new_category_path, :class => "nav-link" %>
      </li>
      <li class="nav-item">
         <%= link_to 'New Post', new_post_path, :class => "nav-link" %>
      </li>
      <li class="nav-item">
         <%= link_to 'All Posts', posts_path, :class => "nav-link" %>
      </li>
      <li class="nav-item">
         <%= link_to 'Update Profile',  edit_user_registration_path, :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Signout', destroy_user_session_path, :method => :delete, :class => "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
         <%= link_to 'Signin', new_user_session_path, :class => "nav-link" %>  
      </li>
      <li class="nav-item">
        <%= link_to 'Signup', new_user_registration_path, :class => "nav-link"  %> 
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/posts/edit.html.erb
<div class="container">
	<%= link_to 'View All Posts', posts_path, :class=> 'text-primary' %>
	<h1 class="text-center">Edit Post</h1>

	<div class="row">
		<div class="col-sm-7 mx-auto">
		 <%= form_for @post, html: { multipart: true, class: 'form-horizontal' } do |f| %>
		      <div class="field form-group form-row">
		        <%= f.label :title, class: 'col-sm-3' %><br />
		        <%= f.text_field :title, class: 'form-control col-sm-7', placeholder: 'Post Title' %>
		      </div>

		      <div class="field form-group form-row">
		        <%= f.label :body, class: 'col-sm-3' %><br />
		        <%= f.text_area :body, class: 'form-control col-sm-7', placeholder: 'Post Description' %>
		      </div>

		        <div class="field form-group form-row">
			        <%= f.label :category, class: 'col-sm-3' %><br />
			        <%= select("post", "category_id", Category.all.collect {|p| [ p.name, p.id ] }, {include_blank: false}, class: 'form-control col-sm-7' ) %>
			      </div>
		       <%= f.hidden_field :user_id, :value => current_user.id %>

		    <div class="field form-group form-row">
		        <div class="col-sm-3"></div>
		        <%= f.submit "Update Post", class: 'col-sm-7 btn btn-warning' %>
		      </div>
		   <% end %>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
<div class="container">
	<h1 class="text-center">Blog Posts</h1>
	<ul class="list-group">
		
		<% @posts.each do |post| %>
		<li class="list-group-item mb-3 w-75">
			<span class="float-right small">Category: <%= link_to post.category.name, category_path(post.category) %> </span>
			<%= link_to post.title, post_path(post) %> <br>
			<% if user_signed_in? %>
				<%= link_to 'Edit', edit_post_path(post), :class=> 'small text-warning mr-2' %>
				 <%= link_to "Delete", post_path(post), :confirm => "Are you sure you want to delete?", :method => :delete, :class=> 'small text-danger' %>
			<% else %>
				<!--<small class="text-danger">Signing to see action buttons</small> -->
			<% end %>
		</li>
	<% end %>
	</ul>	

</div>

app/views/posts/new.html.erb
<div class="container">
	<%= link_to 'All Posts', posts_path, :class=> 'text-primary' %>
	<h1 class="text-center">Create New Post</h1>
	
	<div class="row">
		<div class="col-sm-7 mx-auto">
		 <%= form_for @post, html: { multipart: true, class: 'form-horizontal' } do |f| %>
		      <div class="field form-group form-row">
		        <%= f.label :title, class: 'col-sm-3' %><br />
		        <%= f.text_field :title, class: 'form-control col-sm-7', placeholder: 'Post Title' %>
		      </div>

		      <div class="field form-group form-row">
		        <%= f.label :body, class: 'col-sm-3' %><br />
		        <%= f.text_area :body, class: 'form-control col-sm-7', placeholder: 'Post Description' %>
		      </div>

		      <div class="field form-group form-row">
		        <%= f.label :category, class: 'col-sm-3' %><br />
		        <%= select("post", "category_id", Category.all.collect {|p| [ p.name, p.id ] }, {include_blank: false}, class: 'form-control col-sm-7' ) %>
		      </div>

		       <%= f.hidden_field :user_id, :value => current_user.id %>
		  

		    <div class="field form-group form-row">
		        <div class="col-sm-3"></div>
		        <%= f.submit "Add", class: 'col-sm-7 btn btn-warning' %>
		      </div>
		   <% end %>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="container">
<h1 class="text-center"> <%= @post.title %></h1>
	<p><%= @post.body %></p>
	<%= link_to 'Edit Post', edit_post_path(@post), :class=> 'small text-warning' %>
</div>